In [ ]:
import pandas as pd
import numpy as np

In [ ]:
!pip install smote-variants

In [ ]:
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV, train_test_split
import smote_variants as sv

In [ ]:
def err_metric(CM): 
    TN, FP, FN, TP = CM.ravel()
    precision =(TP)/(TP+FP)
    accuracy_model  =(TP+TN)/(TP+TN+FP+FN)
    recall_score  =(TP)/(TP+FN)
    specificity_value =(TN)/(TN + FP)
      
    False_positive_rate =(FP)/(FP+TN)
    False_negative_rate =(FN)/(FN+TP)
    f1_score =2*(( precision * recall_score)/( precision + recall_score))
    print("Precision value of the model: ",precision)
    print("Accuracy of the model: ",accuracy_model)
    print("Recall of the model: ",recall_score)
    print("Specificity of the model: ",specificity_value)
    print("F1 Score of the model: ",f1_score)
    return [accuracy_model,f1_score]

In [ ]:
dd_30_ces=pd.read_csv('/content/delirium_dataset_catboost_encoded_and_scaled_30.csv')
dd_30_ohees=pd.read_csv('/content/delirium_dataset_ohe_encoded_and_scaled_30.csv')
dd_95_ohees=pd.read_csv('/content/delirium_dataset_ohe_encoded_and_scaled_less100dropped.csv')
dd_95_ces=pd.read_csv('/content/delirium_dataset_catboost_encoded_and_scaled_less100dropped.csv')
#dd_55_ohees=pd.read_csv('/content/delirium_dataset_OHE_encoded_and_scaled_55.csv')
#dd_55_ces=pd.read_csv('/content/delirium_dataset_catboost_encoded_and_scaled_55.csv')

In [ ]:
dd_30_ohees.shape

(8646, 116)

In [ ]:
dd_30_ces.shape

(8646, 28)

In [ ]:
dd_95_ohees.shape

(8646, 158)

In [ ]:
dd_95_ces.shape

(8646, 77)

In [ ]:
dd_95_ohees.drop('Unnamed: 0',axis=1,inplace=True)
dd_55_ces.drop('Unnamed: 0',axis=1,inplace=True)
dd_30_ces.drop('Unnamed: 0',axis=1,inplace=True)
dd_95_ces.drop('Unnamed: 0',axis=1,inplace=True)
dd_30_ohees.drop('Unnamed: 0',axis=1,inplace=True)
dd_55_ohees.drop('Unnamed: 0',axis=1,inplace=True)


# Random Forest

In [ ]:
rf=[]

In [ ]:
y = dd_30_ces["Delirium"].values
X=dd_30_ces.drop(["Delirium"], axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

rfmodel = RandomForestClassifier()
rfmodel.fit(xtrain,ytrain)
print('model')
print(rfmodel)

ypredrf = rfmodel.predict(xtest)
print('confusion matrix')
CM=metrics.confusion_matrix(ytest, ypredrf)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, ypredrf))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, ypredrf)))
auc=metrics.roc_auc_score(ytest, ypredrf)
print('Area under the curve : %f' % (auc))

rf1=err_metric(CM)
rf1.append(auc)
rf.append(rf1)

model
RandomForestClassifier()
confusion matrix
[[2302    3]
 [ 276   13]]
classification report
              precision    recall  f1-score   support

         0.0       0.89      1.00      0.94      2305
         1.0       0.81      0.04      0.09       289

    accuracy                           0.89      2594
   macro avg       0.85      0.52      0.51      2594
weighted avg       0.88      0.89      0.85      2594

Accuracy : 0.892444
Area under the curve : 0.521841
Precision value of the model:  0.8125
Accuracy of the model:  0.892444101773323
Recall of the model:  0.04498269896193772
Specificity of the model:  0.9986984815618222
F1 Score of the model:  0.08524590163934427


In [ ]:
y = dd_30_ohees["Delirium"].values
X=dd_30_ohees.drop(["Delirium"], axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

rfmodel = RandomForestClassifier()
rfmodel.fit(xtrain,ytrain)
print('model')
print(rfmodel)

ypredrf = rfmodel.predict(xtest)
print('confusion matrix')
CM=metrics.confusion_matrix(ytest, ypredrf)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, ypredrf))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, ypredrf)))
auc=metrics.roc_auc_score(ytest, ypredrf)
print('Area under the curve : %f' % (auc))

rf1=err_metric(CM)
rf1.append(auc)
rf.append(rf1)

model
RandomForestClassifier()
confusion matrix
[[2305    0]
 [ 280    9]]
classification report
              precision    recall  f1-score   support

         0.0       0.89      1.00      0.94      2305
         1.0       1.00      0.03      0.06       289

    accuracy                           0.89      2594
   macro avg       0.95      0.52      0.50      2594
weighted avg       0.90      0.89      0.84      2594

Accuracy : 0.892059
Area under the curve : 0.515571
Precision value of the model:  1.0
Accuracy of the model:  0.8920585967617579
Recall of the model:  0.031141868512110725
Specificity of the model:  1.0
F1 Score of the model:  0.060402684563758385


In [ ]:
y = dd_95_ohees["Delirium"].values
X=dd_95_ohees.drop(["Delirium"], axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

rfmodel = RandomForestClassifier()
rfmodel.fit(xtrain,ytrain)
print('model')
print(rfmodel)

ypredrf = rfmodel.predict(xtest)
print('confusion matrix')
CM=metrics.confusion_matrix(ytest, ypredrf)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, ypredrf))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, ypredrf)))
auc=metrics.roc_auc_score(ytest, ypredrf)
print('Area under the curve : %f' % (auc))

rf1=err_metric(CM)
rf1.append(auc)
rf.append(rf1)

model
RandomForestClassifier()
confusion matrix
[[2295    0]
 [ 296    3]]
classification report
              precision    recall  f1-score   support

         0.0       0.89      1.00      0.94      2295
         1.0       1.00      0.01      0.02       299

    accuracy                           0.89      2594
   macro avg       0.94      0.51      0.48      2594
weighted avg       0.90      0.89      0.83      2594

Accuracy : 0.885891
Area under the curve : 0.505017
Precision value of the model:  1.0
Accuracy of the model:  0.8858905165767155
Recall of the model:  0.010033444816053512
Specificity of the model:  1.0
F1 Score of the model:  0.019867549668874173


In [ ]:
y = dd_95_ces["Delirium"].values
X=dd_95_ces.drop(["Delirium"], axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

rfmodel = RandomForestClassifier()
rfmodel.fit(xtrain,ytrain)
print('model')
print(rfmodel)

ypredrf = rfmodel.predict(xtest)
print('confusion matrix')
CM=metrics.confusion_matrix(ytest, ypredrf)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, ypredrf))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, ypredrf)))
auc=metrics.roc_auc_score(ytest, ypredrf)
print('Area under the curve : %f' % (auc))

rf1=err_metric(CM)
rf1.append(auc)
rf.append(rf1)

model
RandomForestClassifier()
confusion matrix
[[2295    0]
 [ 293    6]]
classification report
              precision    recall  f1-score   support

         0.0       0.89      1.00      0.94      2295
         1.0       1.00      0.02      0.04       299

    accuracy                           0.89      2594
   macro avg       0.94      0.51      0.49      2594
weighted avg       0.90      0.89      0.84      2594

Accuracy : 0.887047
Area under the curve : 0.510033
Precision value of the model:  1.0
Accuracy of the model:  0.887047031611411
Recall of the model:  0.020066889632107024
Specificity of the model:  1.0
F1 Score of the model:  0.03934426229508197


In [ ]:

##HIGHEST PERFORMANCE
y = dd_55_ces["Delirium"].values
X=dd_55_ces.drop(["Delirium"], axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

rfmodel = RandomForestClassifier()
rfmodel.fit(xtrain,ytrain)
print('model')
print(rfmodel)

ypredrf = rfmodel.predict(xtest)
print('confusion matrix')
CM=metrics.confusion_matrix(ytest, ypredrf)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, ypredrf))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, ypredrf)))
auc=metrics.roc_auc_score(ytest, ypredrf)
print('Area under the curve : %f' % (auc))

rf1=err_metric(CM)
rf1.append(auc)
rf.append(rf1)

model
RandomForestClassifier()
confusion matrix
[[2303    0]
 [ 280   11]]
classification report
              precision    recall  f1-score   support

         0.0       0.89      1.00      0.94      2303
         1.0       1.00      0.04      0.07       291

    accuracy                           0.89      2594
   macro avg       0.95      0.52      0.51      2594
weighted avg       0.90      0.89      0.85      2594

Accuracy : 0.892059
Area under the curve : 0.518900
Precision value of the model:  1.0
Accuracy of the model:  0.8920585967617579
Recall of the model:  0.037800687285223365
Specificity of the model:  1.0
F1 Score of the model:  0.07284768211920528


In [ ]:
y = dd_55_ohees["Delirium"].values
X=dd_55_ohees.drop(["Delirium"], axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

rfmodel = RandomForestClassifier()
rfmodel.fit(xtrain,ytrain)
print('model')
print(rfmodel)

ypredrf = rfmodel.predict(xtest)
print('confusion matrix')
CM=metrics.confusion_matrix(ytest, ypredrf)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, ypredrf))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, ypredrf)))
auc=metrics.roc_auc_score(ytest, ypredrf)
print('Area under the curve : %f' % (auc))

rf1=err_metric(CM)
rf1.append(auc)
rf.append(rf1)

model
RandomForestClassifier()
confusion matrix
[[2303    0]
 [ 282    9]]
classification report
              precision    recall  f1-score   support

         0.0       0.89      1.00      0.94      2303
         1.0       1.00      0.03      0.06       291

    accuracy                           0.89      2594
   macro avg       0.95      0.52      0.50      2594
weighted avg       0.90      0.89      0.84      2594

Accuracy : 0.891288
Area under the curve : 0.515464
Precision value of the model:  1.0
Accuracy of the model:  0.8912875867386276
Recall of the model:  0.030927835051546393
Specificity of the model:  1.0
F1 Score of the model:  0.06000000000000001


In [ ]:
rf

[[0.8912875867386276, 0.06000000000000001, 0.5154639175257731],
 [0.8920585967617579, 0.07284768211920528, 0.5189003436426117],
 [0.887047031611411, 0.03934426229508197, 0.5100334448160535],
 [0.8858905165767155, 0.019867549668874173, 0.5050167224080268],
 [0.8920585967617579, 0.060402684563758385, 0.5155709342560554],
 [0.892444101773323, 0.08524590163934427, 0.52184059026188]]

In [ ]:
rf2=[]

In [ ]:
ovs='MCT'
y = dd_55_ces["Delirium"].values
X=dd_55_ces.drop(["Delirium"], axis=1)
oversampler= sv.MulticlassOversampling(oversampler=ovs,
                                        oversampler_params={'random_state': 5})
X_samp, y_samp= oversampler.sample(X, y)
xtrain, xtest, ytrain, ytest = train_test_split(X_samp, y_samp, test_size=0.30, random_state=0)
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

rfmodel = RandomForestClassifier()
rfmodel.fit(xtrain,ytrain)
print('model')
print(rfmodel)

ypredrf = rfmodel.predict(xtest)
print('confusion matrix')
CM=metrics.confusion_matrix(ytest, ypredrf)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, ypredrf))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, ypredrf)))
auc=metrics.roc_auc_score(ytest, ypredrf)
print('Area under the curve : %f' % (auc))

rf1=err_metric(CM)
rf1.append(auc)
rf2.append(rf1)

2022-08-24 10:30:10,667:INFO:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
INFO:smote_variants:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
2022-08-24 10:30:10,674:INFO:MulticlassOversampling: Sampling minority class with label: 1.0
INFO:smote_variants:MulticlassOversampling: Sampling minority class with label: 1.0
2022-08-24 10:30:10,681:INFO:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
INFO:smote_variants:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
2022-08

model
RandomForestClassifier()
confusion matrix
[[2280    9]
 [  11 2324]]
classification report
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      2289
         1.0       1.00      1.00      1.00      2335

    accuracy                           1.00      4624
   macro avg       1.00      1.00      1.00      4624
weighted avg       1.00      1.00      1.00      4624

Accuracy : 0.995675
Area under the curve : 0.995679
Precision value of the model:  0.9961423060437206
Accuracy of the model:  0.995674740484429
Recall of the model:  0.995289079229122
Specificity of the model:  0.9960681520314548
F1 Score of the model:  0.9957155098543273


In [ ]:
ovs='MCT'
y = dd_95_ces["Delirium"].values
X=dd_95_ces.drop(["Delirium"], axis=1)
oversampler= sv.MulticlassOversampling(oversampler=ovs,
                                        oversampler_params={'random_state': 5})
X_samp, y_samp= oversampler.sample(X, y)
xtrain, xtest, ytrain, ytest = train_test_split(X_samp, y_samp, test_size=0.30, random_state=0)
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
rfmodel = RandomForestClassifier()
rfmodel.fit(xtrain,ytrain)
print('model')
print(rfmodel)

ypredrf = rfmodel.predict(xtest)
print('confusion matrix')
CM=metrics.confusion_matrix(ytest, ypredrf)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, ypredrf))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, ypredrf)))
auc=metrics.roc_auc_score(ytest, ypredrf)
print('Area under the curve : %f' % (auc))

rf1=err_metric(CM)
rf1.append(auc)
rf2.append(rf1)

2022-08-24 10:30:15,187:INFO:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
INFO:smote_variants:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
2022-08-24 10:30:15,206:INFO:MulticlassOversampling: Sampling minority class with label: 1.0
INFO:smote_variants:MulticlassOversampling: Sampling minority class with label: 1.0
2022-08-24 10:30:15,218:INFO:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
INFO:smote_variants:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
2022-08

model
RandomForestClassifier()
confusion matrix
[[2277    3]
 [   4 2340]]
classification report
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      2280
         1.0       1.00      1.00      1.00      2344

    accuracy                           1.00      4624
   macro avg       1.00      1.00      1.00      4624
weighted avg       1.00      1.00      1.00      4624

Accuracy : 0.998486
Area under the curve : 0.998489
Precision value of the model:  0.998719590268886
Accuracy of the model:  0.9984861591695502
Recall of the model:  0.9982935153583617
Specificity of the model:  0.9986842105263158
F1 Score of the model:  0.9985065073607852


In [ ]:
ovs='MCT'
y = dd_30_ces["Delirium"].values
X=dd_30_ces.drop(["Delirium"], axis=1)
oversampler= sv.MulticlassOversampling(oversampler=ovs,
                                        oversampler_params={'random_state': 5})
X_samp, y_samp= oversampler.sample(X, y)
xtrain, xtest, ytrain, ytest = train_test_split(X_samp, y_samp, test_size=0.30, random_state=0)
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

rfmodel = RandomForestClassifier()
rfmodel.fit(xtrain,ytrain)
print('model')
print(rfmodel)

ypredrf = rfmodel.predict(xtest)
print('confusion matrix')
CM=metrics.confusion_matrix(ytest, ypredrf)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, ypredrf))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, ypredrf)))
auc=metrics.roc_auc_score(ytest, ypredrf)
print('Area under the curve : %f' % (auc))

rf1=err_metric(CM)
rf1.append(auc)
rf2.append(rf1)

2022-08-24 10:30:22,117:INFO:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
INFO:smote_variants:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
2022-08-24 10:30:22,125:INFO:MulticlassOversampling: Sampling minority class with label: 1.0
INFO:smote_variants:MulticlassOversampling: Sampling minority class with label: 1.0
2022-08-24 10:30:22,133:INFO:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
INFO:smote_variants:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
2022-08

model
RandomForestClassifier()
confusion matrix
[[2278    6]
 [   6 2334]]
classification report
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      2284
         1.0       1.00      1.00      1.00      2340

    accuracy                           1.00      4624
   macro avg       1.00      1.00      1.00      4624
weighted avg       1.00      1.00      1.00      4624

Accuracy : 0.997405
Area under the curve : 0.997404
Precision value of the model:  0.9974358974358974
Accuracy of the model:  0.9974048442906575
Recall of the model:  0.9974358974358974
Specificity of the model:  0.9973730297723292
F1 Score of the model:  0.9974358974358974


In [ ]:
rf2

[[0.995674740484429, 0.9957155098543273, 0.9956786156302885],
 [0.9984861591695502, 0.9985065073607852, 0.9984888629423389],
 [0.9974048442906575, 0.9974358974358974, 0.9974044636041134]]

# GAM

In [ ]:
pip install pygam

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.8 MB 15.3 MB/s 


In [ ]:
from pygam import LogisticGAM
y = dd_30_ces["Delirium"].values
X=dd_30_ces.drop(["Delirium"], axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)
gam = LogisticGAM().fit(xtrain, ytrain)
gamprd=gam.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, gamprd)
print()
print('classification report')
print(metrics.classification_report(ytest, gamprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, gamprd)))
print('Area under the curve : %f' % (metrics.roc_auc_score(ytest, gamprd)))

err_metric(CM)
print('\n')
print('\n')

confusion matrix

classification report
              precision    recall  f1-score   support

         0.0       0.89      1.00      0.94      2305
         1.0       0.68      0.05      0.10       289

    accuracy                           0.89      2594
   macro avg       0.79      0.52      0.52      2594
weighted avg       0.87      0.89      0.85      2594

Accuracy : 0.891673
Area under the curve : 0.524433
Precision value of the model:  0.6818181818181818
Accuracy of the model:  0.8916730917501927
Recall of the model:  0.05190311418685121
Specificity of the model:  0.9969631236442517
F1 Score of the model:  0.09646302250803858






In [ ]:
from pygam import LogisticGAM
y = dd_30_ohees["Delirium"].values
X=dd_30_ohees.drop(["Delirium"], axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)

gam = LogisticGAM().fit(xtrain, ytrain)
gamprd=gam.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, gamprd)
print()
print('classification report')
print(metrics.classification_report(ytest, gamprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, gamprd)))
print('Area under the curve : %f' % (metrics.roc_auc_score(ytest, gamprd)))

err_metric(CM)
print('\n')
print('\n')

confusion matrix
[[2291   14]
 [ 277   12]]
classification report
              precision    recall  f1-score   support

         0.0       0.89      0.99      0.94      2305
         1.0       0.46      0.04      0.08       289

    accuracy                           0.89      2594
   macro avg       0.68      0.52      0.51      2594
weighted avg       0.84      0.89      0.84      2594

Accuracy : 0.887818
Area under the curve : 0.517724


In [ ]:
from pygam import LogisticGAM
y = dd_95_ces["Delirium"].values
X=dd_95_ces.drop(["Delirium"], axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)

gam = LogisticGAM().fit(xtrain, ytrain)
gamprd=gam.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, gamprd)
print()
print('classification report')
print(metrics.classification_report(ytest, gamprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, gamprd)))
print('Area under the curve : %f' % (metrics.roc_auc_score(ytest, gamprd)))

err_metric(CM)
print('\n')
print('\n')

/usr/local/lib/python3.7/dist-packages/pygam/pygam.py:592: RuntimeWarning: overflow encountered in square
  self.distribution.V(mu=mu) *
/usr/local/lib/python3.7/dist-packages/pygam/links.py:149: RuntimeWarning: divide by zero encountered in true_divide
  return dist.levels/(mu*(dist.levels - mu))
/usr/local/lib/python3.7/dist-packages/pygam/pygam.py:592: RuntimeWarning: invalid value encountered in multiply
  self.distribution.V(mu=mu) *
/usr/local/lib/python3.7/dist-packages/pygam/links.py:149: RuntimeWarning: overflow encountered in true_divide
  return dist.levels/(mu*(dist.levels - mu))
/usr/local/lib/python3.7/dist-packages/pygam/links.py:133: RuntimeWarning: overflow encountered in exp
  elp = np.exp(lp)
/usr/local/lib/python3.7/dist-packages/pygam/links.py:134: RuntimeWarning: invalid value encountered in true_divide
  return dist.levels * elp / (elp + 1)


confusion matrix
[[2264   31]
 [ 290    9]]
classification report
              precision    recall  f1-score   support

         0.0       0.89      0.99      0.93      2295
         1.0       0.23      0.03      0.05       299

    accuracy                           0.88      2594
   macro avg       0.56      0.51      0.49      2594
weighted avg       0.81      0.88      0.83      2594

Accuracy : 0.876253
Area under the curve : 0.508296


In [ ]:
from pygam import LogisticGAM
y = dd_95_ohees["Delirium"].values
X=dd_95_ohees.drop(["Delirium"], axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)

gam = LogisticGAM().fit(xtrain, ytrain)
gamprd=gam.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, gamprd)
print()
print('classification report')
print(metrics.classification_report(ytest, gamprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, gamprd)))
print('Area under the curve : %f' % (metrics.roc_auc_score(ytest, gamprd)))

err_metric(CM)
print('\n')
print('\n')

/usr/local/lib/python3.7/dist-packages/pygam/pygam.py:592: RuntimeWarning: overflow encountered in square
  self.distribution.V(mu=mu) *
/usr/local/lib/python3.7/dist-packages/pygam/links.py:149: RuntimeWarning: divide by zero encountered in true_divide
  return dist.levels/(mu*(dist.levels - mu))
/usr/local/lib/python3.7/dist-packages/pygam/pygam.py:592: RuntimeWarning: invalid value encountered in multiply
  self.distribution.V(mu=mu) *
/usr/local/lib/python3.7/dist-packages/pygam/links.py:149: RuntimeWarning: overflow encountered in true_divide
  return dist.levels/(mu*(dist.levels - mu))
/usr/local/lib/python3.7/dist-packages/pygam/links.py:133: RuntimeWarning: overflow encountered in exp
  elp = np.exp(lp)
/usr/local/lib/python3.7/dist-packages/pygam/links.py:134: RuntimeWarning: invalid value encountered in true_divide
  return dist.levels * elp / (elp + 1)


confusion matrix
[[2264   31]
 [ 290    9]]
classification report
              precision    recall  f1-score   support

         0.0       0.89      0.99      0.93      2295
         1.0       0.23      0.03      0.05       299

    accuracy                           0.88      2594
   macro avg       0.56      0.51      0.49      2594
weighted avg       0.81      0.88      0.83      2594

Accuracy : 0.876253
Area under the curve : 0.508296


In [ ]:
from pygam import LogisticGAM
y = dd_55_ohees["Delirium"].values
X=dd_55_ohees.drop(["Delirium"], axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)

gam = LogisticGAM().fit(xtrain, ytrain)
gamprd=gam.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, gamprd)
print()
print('classification report')
print(metrics.classification_report(ytest, gamprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, gamprd)))
print('Area under the curve : %f' % (metrics.roc_auc_score(ytest, gamprd)))

err_metric(CM)
print('\n')
print('\n')

/usr/local/lib/python3.7/dist-packages/pygam/links.py:149: RuntimeWarning: divide by zero encountered in true_divide
  return dist.levels/(mu*(dist.levels - mu))
/usr/local/lib/python3.7/dist-packages/pygam/pygam.py:592: RuntimeWarning: invalid value encountered in multiply
  self.distribution.V(mu=mu) *
/usr/local/lib/python3.7/dist-packages/pygam/pygam.py:592: RuntimeWarning: overflow encountered in square
  self.distribution.V(mu=mu) *


did not converge
confusion matrix
[[2277   26]
 [ 264   27]]
classification report
              precision    recall  f1-score   support

         0.0       0.90      0.99      0.94      2303
         1.0       0.51      0.09      0.16       291

    accuracy                           0.89      2594
   macro avg       0.70      0.54      0.55      2594
weighted avg       0.85      0.89      0.85      2594

Accuracy : 0.888204
Area under the curve : 0.540747


In [ ]:
#from pygam import LogisticGAM
#y = dd_55_ces["Delirium"].values
#X=dd_55_ces.drop(["Delirium"], axis=1)
#xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)

#gam = LogisticGAM(fit_intercept=True).fit(xtrain, ytrain)
#gamprd=gam.predict(xtest)

#print('confusion matrix')
#print(metrics.confusion_matrix(ytest, gamprd))
#print('classification report')
#print(metrics.classification_report(ytest, gamprd))
#print('Accuracy : %f' % (metrics.accuracy_score(ytest, gamprd)))
#print('Area under the curve : %f' % (metrics.roc_auc_score(ytest, gamprd)))

In [ ]:
ovs='MCT'
y = dd_30_ces["Delirium"].values
X=dd_30_ces.drop(["Delirium"], axis=1)
oversampler= sv.MulticlassOversampling(oversampler=ovs,
                                        oversampler_params={'random_state': 5})
X_samp, y_samp= oversampler.sample(X, y)
xtrain, xtest, ytrain, ytest = train_test_split(X_samp, y_samp, test_size=0.30, random_state=0)

gam = LogisticGAM().fit(xtrain, ytrain)
gamprd=gam.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, gamprd)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, gamprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, gamprd)))
print('Area under the curve : %f' % (metrics.roc_auc_score(ytest, gamprd)))

err_metric(CM)
print('\n')
print('\n')

2022-08-24 09:22:10,063:INFO:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
INFO:smote_variants:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
2022-08-24 09:22:10,080:INFO:MulticlassOversampling: Sampling minority class with label: 1.0
INFO:smote_variants:MulticlassOversampling: Sampling minority class with label: 1.0
2022-08-24 09:22:10,092:INFO:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
INFO:smote_variants:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
2022-08

did not converge
confusion matrix
[[1572  712]
 [ 657 1683]]
classification report
              precision    recall  f1-score   support

         0.0       0.71      0.69      0.70      2284
         1.0       0.70      0.72      0.71      2340

    accuracy                           0.70      4624
   macro avg       0.70      0.70      0.70      4624
weighted avg       0.70      0.70      0.70      4624

Accuracy : 0.703936
Area under the curve : 0.703748
Precision value of the model:  0.702713987473904
Accuracy of the model:  0.7039359861591695
Recall of the model:  0.7192307692307692
Specificity of the model:  0.6882661996497373






In [ ]:
ovs='MCT'
y = dd_30_ohees["Delirium"].values
X=dd_30_ohees.drop(["Delirium"], axis=1)
oversampler= sv.MulticlassOversampling(oversampler=ovs,
                                        oversampler_params={'random_state': 5})
X_samp, y_samp= oversampler.sample(X, y)
xtrain, xtest, ytrain, ytest = train_test_split(X_samp, y_samp, test_size=0.30, random_state=0)

gam = LogisticGAM().fit(xtrain, ytrain)
gamprd=gam.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, gamprd)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, gamprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, gamprd)))
print('Area under the curve : %f' % (metrics.roc_auc_score(ytest, gamprd)))

err_metric(CM)
print('\n')
print('\n')

2022-08-24 09:25:53,851:INFO:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
INFO:smote_variants:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
2022-08-24 09:25:53,865:INFO:MulticlassOversampling: Sampling minority class with label: 1.0
INFO:smote_variants:MulticlassOversampling: Sampling minority class with label: 1.0
2022-08-24 09:25:53,882:INFO:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
INFO:smote_variants:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
2022-08

confusion matrix
[[1610  674]
 [ 696 1644]]
classification report
              precision    recall  f1-score   support

         0.0       0.70      0.70      0.70      2284
         1.0       0.71      0.70      0.71      2340

    accuracy                           0.70      4624
   macro avg       0.70      0.70      0.70      4624
weighted avg       0.70      0.70      0.70      4624

Accuracy : 0.703720
Area under the curve : 0.703734
Precision value of the model:  0.7092320966350302
Accuracy of the model:  0.703719723183391
Recall of the model:  0.7025641025641025
Specificity of the model:  0.7049036777583187






# CART

In [ ]:
cart=[]

In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()   
y = dd_30_ces["Delirium"].values
X=dd_30_ces.drop(["Delirium"], axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)
clf.fit(xtrain,ytrain)
clfprd=clf.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, clfprd)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, clfprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, clfprd)))
auc=metrics.roc_auc_score(ytest, clfprd)
print('Area under the curve : %f' % (auc))

cart1=err_metric(CM)
cart1.append(auc)
cart.append(cart1)
print('\n')
print('\n')

confusion matrix
[[2055  250]
 [ 229   60]]
classification report
              precision    recall  f1-score   support

         0.0       0.90      0.89      0.90      2305
         1.0       0.19      0.21      0.20       289

    accuracy                           0.82      2594
   macro avg       0.55      0.55      0.55      2594
weighted avg       0.82      0.82      0.82      2594

Accuracy : 0.815343
Area under the curve : 0.549576
Precision value of the model:  0.1935483870967742
Accuracy of the model:  0.8153430994602929
Recall of the model:  0.20761245674740483
Specificity of the model:  0.8915401301518439
F1 Score of the model:  0.2003338898163606






In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()   
y = dd_55_ces["Delirium"].values
X=dd_55_ces.drop(["Delirium"], axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)
clf.fit(xtrain,ytrain)
clfprd=clf.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, clfprd)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, clfprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, clfprd)))
auc=metrics.roc_auc_score(ytest, clfprd)
print('Area under the curve : %f' % (auc))

cart1=err_metric(CM)
cart1.append(auc)
cart.append(cart1)
print('\n')
print('\n')

confusion matrix
[[2051  252]
 [ 233   58]]
classification report
              precision    recall  f1-score   support

         0.0       0.90      0.89      0.89      2303
         1.0       0.19      0.20      0.19       291

    accuracy                           0.81      2594
   macro avg       0.54      0.54      0.54      2594
weighted avg       0.82      0.81      0.82      2594

Accuracy : 0.813030
Area under the curve : 0.544945
Precision value of the model:  0.1870967741935484
Accuracy of the model:  0.813030069390902
Recall of the model:  0.19931271477663232
Specificity of the model:  0.8905775075987842
F1 Score of the model:  0.19301164725457573






In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()   
y = dd_95_ces["Delirium"].values
X=dd_95_ces.drop(["Delirium"], axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)
clf.fit(xtrain,ytrain)
clfprd=clf.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, clfprd)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, clfprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, clfprd)))
auc=metrics.roc_auc_score(ytest, clfprd)
print('Area under the curve : %f' % (auc))

cart1=err_metric(CM)
cart1.append(auc)
cart.append(cart1)
print('\n')
print('\n')

confusion matrix
[[2031  264]
 [ 254   45]]
classification report
              precision    recall  f1-score   support

         0.0       0.89      0.88      0.89      2295
         1.0       0.15      0.15      0.15       299

    accuracy                           0.80      2594
   macro avg       0.52      0.52      0.52      2594
weighted avg       0.80      0.80      0.80      2594

Accuracy : 0.800308
Area under the curve : 0.517734
Precision value of the model:  0.14563106796116504
Accuracy of the model:  0.8003084040092521
Recall of the model:  0.1505016722408027
Specificity of the model:  0.8849673202614379
F1 Score of the model:  0.14802631578947367






In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()   
y = dd_30_ohees["Delirium"].values
X=dd_30_ohees.drop(["Delirium"], axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)
clf.fit(xtrain,ytrain)
clfprd=clf.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, clfprd)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, clfprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, clfprd)))
auc=metrics.roc_auc_score(ytest, clfprd)
print('Area under the curve : %f' % (auc))

cart1=err_metric(CM)
cart1.append(auc)
cart.append(cart1)
print('\n')
print('\n')

confusion matrix
[[2066  239]
 [ 219   70]]
classification report
              precision    recall  f1-score   support

         0.0       0.90      0.90      0.90      2305
         1.0       0.23      0.24      0.23       289

    accuracy                           0.82      2594
   macro avg       0.57      0.57      0.57      2594
weighted avg       0.83      0.82      0.83      2594

Accuracy : 0.823439
Area under the curve : 0.569263
Precision value of the model:  0.22653721682847897
Accuracy of the model:  0.8234387047031612
Recall of the model:  0.2422145328719723
Specificity of the model:  0.8963123644251627
F1 Score of the model:  0.23411371237458195






In [ ]:
#HIGHEST PERFORMANCE

from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()   
y = dd_55_ohees["Delirium"].values
X=dd_55_ohees.drop(["Delirium"], axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)
clf.fit(xtrain,ytrain)
clfprd=clf.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, clfprd)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, clfprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, clfprd)))
auc=metrics.roc_auc_score(ytest, clfprd)
print('Area under the curve : %f' % (auc))

cart1=err_metric(CM)
cart1.append(auc)
cart.append(cart1)
print('\n')
print('\n')

confusion matrix
[[2070  233]
 [ 224   67]]
classification report
              precision    recall  f1-score   support

         0.0       0.90      0.90      0.90      2303
         1.0       0.22      0.23      0.23       291

    accuracy                           0.82      2594
   macro avg       0.56      0.56      0.56      2594
weighted avg       0.83      0.82      0.82      2594

Accuracy : 0.823824
Area under the curve : 0.564534
Precision value of the model:  0.22333333333333333
Accuracy of the model:  0.8238242097147263
Recall of the model:  0.23024054982817868
Specificity of the model:  0.8988276161528441






In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()   
y = dd_95_ohees["Delirium"].values
X=dd_95_ohees.drop(["Delirium"], axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)
clf.fit(xtrain,ytrain)
clfprd=clf.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, clfprd)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, clfprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, clfprd)))
auc=metrics.roc_auc_score(ytest, clfprd)
print('Area under the curve : %f' % (auc))

cart1=err_metric(CM)
cart1.append(auc)
cart.append(cart1)
print('\n')
print('\n')

confusion matrix
[[1973  322]
 [ 251   48]]
classification report
              precision    recall  f1-score   support

         0.0       0.89      0.86      0.87      2295
         1.0       0.13      0.16      0.14       299

    accuracy                           0.78      2594
   macro avg       0.51      0.51      0.51      2594
weighted avg       0.80      0.78      0.79      2594

Accuracy : 0.779106
Area under the curve : 0.510115
Precision value of the model:  0.12972972972972974
Accuracy of the model:  0.7791056283731689
Recall of the model:  0.1605351170568562
Specificity of the model:  0.8596949891067538
F1 Score of the model:  0.14349775784753366






In [ ]:
cart

[[0.8153430994602929, 0.2003338898163606, 0.5495762934496244],
 [0.813030069390902, 0.19301164725457573, 0.5449451111877083],
 [0.8003084040092521, 0.14802631578947367, 0.5177344962511203],
 [0.8234387047031612, 0.23411371237458195, 0.5692634486485675],
 [0.7791056283731689, 0.14349775784753366, 0.5101150530818049],
 [0.9377162629757786, 0.9419822723609991, 0.9369631924798298],
 [0.9355536332179931, 0.9400161030595813, 0.9347897675393297],
 [0.9372837370242214, 0.9412717699473471, 0.9367008961021102]]

In [ ]:
from sklearn.tree import DecisionTreeClassifier

ovs='MCT'
y = dd_30_ces["Delirium"].values
X=dd_30_ces.drop(["Delirium"], axis=1)
oversampler= sv.MulticlassOversampling(oversampler=ovs,
                                        oversampler_params={'random_state': 5})
X_samp, y_samp= oversampler.sample(X, y)
xtrain, xtest, ytrain, ytest = train_test_split(X_samp, y_samp, test_size=0.30, random_state=0)
clf = DecisionTreeClassifier()   
clf.fit(xtrain,ytrain)
clfprd=clf.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, clfprd)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, clfprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, clfprd)))
auc=metrics.roc_auc_score(ytest, clfprd)
print('Area under the curve : %f' % (auc))

cart1=err_metric(CM)
cart1.append(auc)
cart.append(cart1)
print('\n')
print('\n')

2022-08-24 10:33:25,618:INFO:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
INFO:smote_variants:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
2022-08-24 10:33:25,632:INFO:MulticlassOversampling: Sampling minority class with label: 1.0
INFO:smote_variants:MulticlassOversampling: Sampling minority class with label: 1.0
2022-08-24 10:33:25,640:INFO:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
INFO:smote_variants:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
2022-08

confusion matrix
[[1998  286]
 [   2 2338]]
classification report
              precision    recall  f1-score   support

         0.0       1.00      0.87      0.93      2284
         1.0       0.89      1.00      0.94      2340

    accuracy                           0.94      4624
   macro avg       0.95      0.94      0.94      4624
weighted avg       0.94      0.94      0.94      4624

Accuracy : 0.937716
Area under the curve : 0.936963
Precision value of the model:  0.8910060975609756
Accuracy of the model:  0.9377162629757786
Recall of the model:  0.9991452991452991
Specificity of the model:  0.8747810858143608
F1 Score of the model:  0.9419822723609991






In [ ]:
ovs='MCT'
y = dd_30_ohees["Delirium"].values
X=dd_30_ohees.drop(["Delirium"], axis=1)
oversampler= sv.MulticlassOversampling(oversampler=ovs,
                                        oversampler_params={'random_state': 5})
X_samp, y_samp= oversampler.sample(X, y)
xtrain, xtest, ytrain, ytest = train_test_split(X_samp, y_samp, test_size=0.30, random_state=0)
clf = DecisionTreeClassifier()   
clf.fit(xtrain,ytrain)
clfprd=clf.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, clfprd)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, clfprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, clfprd)))
auc=metrics.roc_auc_score(ytest, clfprd)
print('Area under the curve : %f' % (auc))

cart1=err_metric(CM)
cart1.append(auc)
cart.append(cart1)
print('\n')
print('\n')

2022-08-24 10:33:34,629:INFO:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
INFO:smote_variants:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
2022-08-24 10:33:34,640:INFO:MulticlassOversampling: Sampling minority class with label: 1.0
INFO:smote_variants:MulticlassOversampling: Sampling minority class with label: 1.0
2022-08-24 10:33:34,652:INFO:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
INFO:smote_variants:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
2022-08

confusion matrix
[[1991  293]
 [   5 2335]]
classification report
              precision    recall  f1-score   support

         0.0       1.00      0.87      0.93      2284
         1.0       0.89      1.00      0.94      2340

    accuracy                           0.94      4624
   macro avg       0.94      0.93      0.94      4624
weighted avg       0.94      0.94      0.94      4624

Accuracy : 0.935554
Area under the curve : 0.934790
Precision value of the model:  0.8885083713850838
Accuracy of the model:  0.9355536332179931
Recall of the model:  0.9978632478632479
Specificity of the model:  0.8717162872154116
F1 Score of the model:  0.9400161030595813






In [ ]:
ovs='MCT'
y = dd_55_ohees["Delirium"].values
X=dd_55_ohees.drop(["Delirium"], axis=1)
oversampler= sv.MulticlassOversampling(oversampler=ovs,
                                        oversampler_params={'random_state': 5})
X_samp, y_samp= oversampler.sample(X, y)
xtrain, xtest, ytrain, ytest = train_test_split(X_samp, y_samp, test_size=0.30, random_state=0)
clf = DecisionTreeClassifier()   
clf.fit(xtrain,ytrain)
clfprd=clf.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, clfprd)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, clfprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, clfprd)))
auc=metrics.roc_auc_score(ytest, clfprd)
print('Area under the curve : %f' % (auc))

cart1=err_metric(CM)
cart1.append(auc)
cart.append(cart1)
print('\n')
print('\n')

2022-08-24 10:35:18,819:INFO:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
INFO:smote_variants:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
2022-08-24 10:35:18,836:INFO:MulticlassOversampling: Sampling minority class with label: 1.0
INFO:smote_variants:MulticlassOversampling: Sampling minority class with label: 1.0
2022-08-24 10:35:18,854:INFO:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
INFO:smote_variants:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
2022-08

confusion matrix
[[2010  279]
 [  11 2324]]
classification report
              precision    recall  f1-score   support

         0.0       0.99      0.88      0.93      2289
         1.0       0.89      1.00      0.94      2335

    accuracy                           0.94      4624
   macro avg       0.94      0.94      0.94      4624
weighted avg       0.94      0.94      0.94      4624

Accuracy : 0.937284
Area under the curve : 0.936701
Precision value of the model:  0.8928159815597387
Accuracy of the model:  0.9372837370242214
Recall of the model:  0.995289079229122
Specificity of the model:  0.8781127129750983
F1 Score of the model:  0.9412717699473471






# SVM

In [ ]:
svm=[]

In [ ]:
from sklearn.svm import SVC

In [ ]:
y = dd_30_ces["Delirium"].values
X=dd_30_ces.drop(["Delirium"], axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)
clf = SVC(kernel='linear')
clf.fit(xtrain, ytrain)
svcprd = clf.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, svcprd)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, svcprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, svcprd)))
auc=metrics.roc_auc_score(ytest, svcprd)
print('Area under the curve : %f' % (auc))

svm1=err_metric(CM)
svm1.append(auc)
svm.append(svm1)
print('\n')
print('\n')

confusion matrix
[[2305    0]
 [ 289    0]]
classification report
              precision    recall  f1-score   support

         0.0       0.89      1.00      0.94      2305
         1.0       0.00      0.00      0.00       289

    accuracy                           0.89      2594
   macro avg       0.44      0.50      0.47      2594
weighted avg       0.79      0.89      0.84      2594

Accuracy : 0.888589
Area under the curve : 0.500000
Precision value of the model:  nan
Accuracy of the model:  0.8885890516576715
Recall of the model:  0.0
Specificity of the model:  1.0
F1 Score of the model:  nan






/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: Run

In [ ]:
y = dd_55_ces["Delirium"].values
X=dd_55_ces.drop(["Delirium"], axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)
clf = SVC(kernel='linear')
clf.fit(xtrain, ytrain)
svcprd = clf.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, svcprd)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, svcprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, svcprd)))
auc=metrics.roc_auc_score(ytest, svcprd)
print('Area under the curve : %f' % (auc))

svm1=err_metric(CM)
svm1.append(auc)
svm.append(svm1)
print('\n')
print('\n')

confusion matrix
[[2303    0]
 [ 291    0]]
classification report
              precision    recall  f1-score   support

         0.0       0.89      1.00      0.94      2303
         1.0       0.00      0.00      0.00       291

    accuracy                           0.89      2594
   macro avg       0.44      0.50      0.47      2594
weighted avg       0.79      0.89      0.84      2594

Accuracy : 0.887818
Area under the curve : 0.500000
Precision value of the model:  nan
Accuracy of the model:  0.8878180416345413
Recall of the model:  0.0
Specificity of the model:  1.0
F1 Score of the model:  nan






/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: Run

In [ ]:
y = dd_95_ces["Delirium"].values
X=dd_95_ces.drop(["Delirium"], axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)
clf = SVC(kernel='linear')
clf.fit(xtrain, ytrain)
svcprd = clf.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, svcprd)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, svcprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, svcprd)))
auc=metrics.roc_auc_score(ytest, svcprd)
print('Area under the curve : %f' % (auc))

svm1=err_metric(CM)
svm1.append(auc)
svm.append(svm1)
print('\n')
print('\n')

confusion matrix
[[2295    0]
 [ 299    0]]
classification report
              precision    recall  f1-score   support

         0.0       0.88      1.00      0.94      2295
         1.0       0.00      0.00      0.00       299

    accuracy                           0.88      2594
   macro avg       0.44      0.50      0.47      2594
weighted avg       0.78      0.88      0.83      2594

Accuracy : 0.884734
Area under the curve : 0.500000
Precision value of the model:  nan
Accuracy of the model:  0.8847340015420201
Recall of the model:  0.0
Specificity of the model:  1.0
F1 Score of the model:  nan






/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: Run

In [ ]:
y = dd_30_ohees["Delirium"].values
X=dd_30_ohees.drop(["Delirium"], axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)
clf = SVC(kernel='linear')
clf.fit(xtrain, ytrain)
svcprd = clf.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, svcprd)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, svcprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, svcprd)))
auc=metrics.roc_auc_score(ytest, svcprd)
print('Area under the curve : %f' % (auc))

svm1=err_metric(CM)
svm1.append(auc)
svm.append(svm1)
print('\n')
print('\n')

confusion matrix
[[2305    0]
 [ 285    4]]
classification report
              precision    recall  f1-score   support

         0.0       0.89      1.00      0.94      2305
         1.0       1.00      0.01      0.03       289

    accuracy                           0.89      2594
   macro avg       0.94      0.51      0.48      2594
weighted avg       0.90      0.89      0.84      2594

Accuracy : 0.890131
Area under the curve : 0.506920
Precision value of the model:  1.0
Accuracy of the model:  0.8901310717039321
Recall of the model:  0.01384083044982699
Specificity of the model:  1.0
F1 Score of the model:  0.027303754266211604






In [ ]:
y = dd_55_ohees["Delirium"].values
X=dd_55_ohees.drop(["Delirium"], axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)
clf = SVC(kernel='linear')
clf.fit(xtrain, ytrain)
svcprd = clf.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, svcprd)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, svcprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, svcprd)))
auc=metrics.roc_auc_score(ytest, svcprd)
print('Area under the curve : %f' % (auc))

svm1=err_metric(CM)
svm1.append(auc)
svm.append(svm1)
print('\n')
print('\n')

confusion matrix
[[2301    2]
 [ 288    3]]
classification report
              precision    recall  f1-score   support

         0.0       0.89      1.00      0.94      2303
         1.0       0.60      0.01      0.02       291

    accuracy                           0.89      2594
   macro avg       0.74      0.50      0.48      2594
weighted avg       0.86      0.89      0.84      2594

Accuracy : 0.888204
Area under the curve : 0.504720
Precision value of the model:  0.6
Accuracy of the model:  0.8882035466461063
Recall of the model:  0.010309278350515464
Specificity of the model:  0.9991315675206253
F1 Score of the model:  0.02027027027027027






In [ ]:
y = dd_95_ohees["Delirium"].values
X=dd_95_ohees.drop(["Delirium"], axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=0)
clf = SVC(kernel='linear')
clf.fit(xtrain, ytrain)
svcprd = clf.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, svcprd)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, svcprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, svcprd)))
auc=metrics.roc_auc_score(ytest, svcprd)
print('Area under the curve : %f' % (auc))

svm1=err_metric(CM)
svm1.append(auc)
svm.append(svm1)
print('\n')
print('\n')

confusion matrix
[[2291    4]
 [ 294    5]]
classification report
              precision    recall  f1-score   support

         0.0       0.89      1.00      0.94      2295
         1.0       0.56      0.02      0.03       299

    accuracy                           0.89      2594
   macro avg       0.72      0.51      0.49      2594
weighted avg       0.85      0.89      0.83      2594

Accuracy : 0.885120
Area under the curve : 0.507490
Precision value of the model:  0.5555555555555556
Accuracy of the model:  0.8851195065535852
Recall of the model:  0.016722408026755852
Specificity of the model:  0.9982570806100218
F1 Score of the model:  0.03246753246753247






In [ ]:
svm

[[0.8885890516576715, nan, 0.5],
 [0.8878180416345413, nan, 0.5],
 [0.8847340015420201, nan, 0.5],
 [0.8901310717039321, 0.027303754266211604, 0.5069204152249135],
 [0.8882035466461063, 0.02027027027027027, 0.5047204229355704],
 [0.8851195065535852, 0.03246753246753247, 0.5074897443183889]]

In [ ]:
svm2=[]

In [ ]:
ovs='MCT'
y = dd_30_ces["Delirium"].values
X=dd_30_ces.drop(["Delirium"], axis=1)
oversampler= sv.MulticlassOversampling(oversampler=ovs,
                                        oversampler_params={'random_state': 5})
X_samp, y_samp= oversampler.sample(X, y)
xtrain, xtest, ytrain, ytest = train_test_split(X_samp, y_samp, test_size=0.30, random_state=0)

clf = SVC(kernel='linear')
clf.fit(xtrain, ytrain)
svcprd = clf.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, svcprd)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, svcprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, svcprd)))
auc=metrics.roc_auc_score(ytest, svcprd)
print('Area under the curve : %f' % (auc))

svm1=err_metric(CM)
svm1.append(auc)
svm2.append(svm1)
print('\n')
print('\n')

2022-08-24 10:41:54,969:INFO:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
INFO:smote_variants:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
2022-08-24 10:41:54,975:INFO:MulticlassOversampling: Sampling minority class with label: 1.0
INFO:smote_variants:MulticlassOversampling: Sampling minority class with label: 1.0
2022-08-24 10:41:54,982:INFO:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
INFO:smote_variants:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
2022-08

confusion matrix
[[1657  627]
 [1088 1252]]
classification report
              precision    recall  f1-score   support

         0.0       0.60      0.73      0.66      2284
         1.0       0.67      0.54      0.59      2340

    accuracy                           0.63      4624
   macro avg       0.63      0.63      0.63      4624
weighted avg       0.64      0.63      0.63      4624

Accuracy : 0.629109
Area under the curve : 0.630262
Precision value of the model:  0.6663118680149015
Accuracy of the model:  0.6291089965397924
Recall of the model:  0.535042735042735
Specificity of the model:  0.7254816112084063
F1 Score of the model:  0.5935055700402939






In [ ]:
ovs='MCT'
y = dd_30_ohees["Delirium"].values
X=dd_30_ohees.drop(["Delirium"], axis=1)
oversampler= sv.MulticlassOversampling(oversampler=ovs,
                                        oversampler_params={'random_state': 5})
X_samp, y_samp= oversampler.sample(X, y)
xtrain, xtest, ytrain, ytest = train_test_split(X_samp, y_samp, test_size=0.30, random_state=0)

clf = SVC(kernel='linear')
clf.fit(xtrain, ytrain)
svcprd = clf.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, svcprd)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, svcprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, svcprd)))
auc=metrics.roc_auc_score(ytest, svcprd)
print('Area under the curve : %f' % (auc))

svm1=err_metric(CM)
svm1.append(auc)
svm2.append(svm1)
print('\n')
print('\n')

2022-08-24 10:42:10,154:INFO:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
INFO:smote_variants:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
2022-08-24 10:42:10,175:INFO:MulticlassOversampling: Sampling minority class with label: 1.0
INFO:smote_variants:MulticlassOversampling: Sampling minority class with label: 1.0
2022-08-24 10:42:10,219:INFO:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
INFO:smote_variants:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
2022-08

confusion matrix
[[1413  871]
 [ 810 1530]]
classification report
              precision    recall  f1-score   support

         0.0       0.64      0.62      0.63      2284
         1.0       0.64      0.65      0.65      2340

    accuracy                           0.64      4624
   macro avg       0.64      0.64      0.64      4624
weighted avg       0.64      0.64      0.64      4624

Accuracy : 0.636462
Area under the curve : 0.636249
Precision value of the model:  0.6372344856309871
Accuracy of the model:  0.636461937716263
Recall of the model:  0.6538461538461539
Specificity of the model:  0.6186514886164624
F1 Score of the model:  0.6454334528580468






In [ ]:
ovs='MCT'
y = dd_95_ohees["Delirium"].values
X=dd_95_ohees.drop(["Delirium"], axis=1)
oversampler= sv.MulticlassOversampling(oversampler=ovs,
                                        oversampler_params={'random_state': 5})
X_samp, y_samp= oversampler.sample(X, y)
xtrain, xtest, ytrain, ytest = train_test_split(X_samp, y_samp, test_size=0.30, random_state=0)

clf = SVC(kernel='linear')
clf.fit(xtrain, ytrain)
svcprd = clf.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, svcprd)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, svcprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, svcprd)))
auc=metrics.roc_auc_score(ytest, svcprd)
print('Area under the curve : %f' % (auc))

svm1=err_metric(CM)
svm1.append(auc)
svm2.append(svm1)
print('\n')
print('\n')

2022-08-24 10:42:26,159:INFO:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
INFO:smote_variants:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
2022-08-24 10:42:26,176:INFO:MulticlassOversampling: Sampling minority class with label: 1.0
INFO:smote_variants:MulticlassOversampling: Sampling minority class with label: 1.0
2022-08-24 10:42:26,197:INFO:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
INFO:smote_variants:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
2022-08

confusion matrix
[[1437  843]
 [ 702 1642]]
classification report
              precision    recall  f1-score   support

         0.0       0.67      0.63      0.65      2280
         1.0       0.66      0.70      0.68      2344

    accuracy                           0.67      4624
   macro avg       0.67      0.67      0.67      4624
weighted avg       0.67      0.67      0.67      4624

Accuracy : 0.665874
Area under the curve : 0.665388
Precision value of the model:  0.6607645875251509
Accuracy of the model:  0.6658737024221453
Recall of the model:  0.7005119453924915
Specificity of the model:  0.6302631578947369
F1 Score of the model:  0.6800579830192587






In [ ]:
ovs='MCT'
y = dd_95_ces["Delirium"].values
X=dd_95_ces.drop(["Delirium"], axis=1)
oversampler= sv.MulticlassOversampling(oversampler=ovs,
                                        oversampler_params={'random_state': 5})
X_samp, y_samp= oversampler.sample(X, y)
xtrain, xtest, ytrain, ytest = train_test_split(X_samp, y_samp, test_size=0.30, random_state=0)

clf = SVC(kernel='linear')
clf.fit(xtrain, ytrain)
svcprd = clf.predict(xtest)

print('confusion matrix')
CM=metrics.confusion_matrix(ytest, svcprd)
print(CM)
print('classification report')
print(metrics.classification_report(ytest, svcprd))
print('Accuracy : %f' % (metrics.accuracy_score(ytest, svcprd)))
auc=metrics.roc_auc_score(ytest, svcprd)
print('Area under the curve : %f' % (auc))

svm1=err_metric(CM)
svm1.append(auc)
svm2.append(svm1)
print('\n')
print('\n')

2022-08-24 10:42:41,384:INFO:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
INFO:smote_variants:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
2022-08-24 10:42:41,392:INFO:MulticlassOversampling: Sampling minority class with label: 1.0
INFO:smote_variants:MulticlassOversampling: Sampling minority class with label: 1.0
2022-08-24 10:42:41,402:INFO:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
INFO:smote_variants:MCT: Running sampling via ('MCT', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 1, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'MCT'}")
2022-08

confusion matrix
[[1282  998]
 [ 720 1624]]
classification report
              precision    recall  f1-score   support

         0.0       0.64      0.56      0.60      2280
         1.0       0.62      0.69      0.65      2344

    accuracy                           0.63      4624
   macro avg       0.63      0.63      0.63      4624
weighted avg       0.63      0.63      0.63      4624

Accuracy : 0.628460
Area under the curve : 0.627557
Precision value of the model:  0.6193745232646835
Accuracy of the model:  0.6284602076124568
Recall of the model:  0.6928327645051194
Specificity of the model:  0.5622807017543859
F1 Score of the model:  0.6540475231574707






In [ ]:
svm2

[[0.6291089965397924, 0.5935055700402939, 0.6302621731255706],
 [0.636461937716263, 0.6454334528580468, 0.6362488212313081],
 [0.6658737024221453, 0.6800579830192587, 0.6653875516436142],
 [0.6284602076124568, 0.6540475231574707, 0.6275567331297527]]